# Generated by Django 2.2.7 on 2019-12-02 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('flavours', models.CharField(choices=[('MARGARITA', 'Margarita'), ('MARINARA', 'Marinara'), ('SALAMI', 'Salami')], max_length=20)),
                ('number', models.IntegerField()),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', max_length=10)),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_address', models.TextField()),
                ('ordered_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(default='open', editable=False, max_length=20)),
            ],
        ),
    ]
