# Generated by Django 2.2.7 on 2019-12-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
