# Generated by Django 2.2.7 on 2019-12-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_auto_20191204_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ACCEPTED', 'Accepted'), ('PREPARING', 'Preparing'), ('OUT FOR DELIVERY', 'Out for Delivery'), ('Delivered', 'Delivered')], default='OPEN', max_length=20),
        ),
    ]
