# Generated by Django 2.2.7 on 2019-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0004_auto_20191204_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='number',
            field=models.IntegerField(default=1, max_length=20),
        ),
    ]
